require('lsp.lua_ls')
require('lsp.docker')
require('lsp.texlab')
require('lsp.rust')
require('lsp.gopls')
-- require('lsp.kotlin')
require('lsp.julia')
require('lsp.weblsps')
require('lsp.cxx')
require('lsp.bash')
