require("plugins.colorscheme")
require("plugins.treesitter")
require("plugins.mini")
require("plugins.oil")
require("plugins.undotree")
require("plugins.lsp")
require("plugins.autocomplete")
require("plugins.vimtex")
