vim.pack.add({
  "https://github.com/nvim-mini/mini.pairs",
  "https://github.com/nvim-mini/mini.hipatterns",
  "https://github.com/nvim-mini/mini.indentscope",
  "https://github.com/nvim-mini/mini.icons",
})
require('mini.pairs').setup()
require('mini.hipatterns').setup()
require('mini.indentscope').setup()
require('mini.icons').setup()
