local function map(m, k, v)
  vim.keymap.set(m, k, v, { silent = false })
end
map('n', '<leader>rn', "<Plug>(vimtex-env-change)")
map('n', 'gns', "<Plug>(vimtex-]])")
map('n', 'gps', "<Plug>(vimtex-[[)")
-- map('n', '<Tab>st', "<Plug>(vimtex-cmd-toggle-star)")
map('n', '<Tab>st', "<Plug>(vimtex-env-toggle-star)")
map('n', '<Tab>f', "<Plug>(vimtex-cmd-toggle-frac)")
map('n', '<Tab>m', "<Plug>(vimtex-delim-toggle-modifier)")
map('n', '<leader>lt', "<Plug>(vimtex-toc-toggle)")
map('n', '<leader>ll', "<Plug>(vimtex-compile)")
map('v', 'ie', "<Plug>(vimtex-ie)")
map('v', 'ae', "<Plug>(vimtex-ae)")
